### ISSUE TITLE
Bug in TypeScript Templates

### ISSUE THREAD

**Issue by mbe1987** [commercetools/connect-application-kit#52]
There are some issues concerning the provided service app in TypeScript template:

-  post-deploy.ts and pre-undeploy.ts should start with
`import * as dotenv from 'dotenv';
dotenv.config();`
- in the switch statement of the service.controller.ts, the cases should be payment and order instead of payments and orders
- the dependency "@tsconfig/node16" is missing from package.json so that "extends": "@tsconfig/node16/tsconfig.json" from tsconfig.json works

**Comment by ruidias-commercetools** [comment]
Hi @mbe1987, thank you for opening this issue.

Regarding the first tick on the issue list, what is your motivation to use `.dotenv` library in the `post-deploy.js` script?

Thanks, 
Rui

**Comment by abreu-ct** [comment]
Thank you @mbe1987 for reporting those issues. We have made the fixes in https://github.com/commercetools/connect-application-kit/pull/57.
