### ISSUE TITLE
Error when executing build command inside event typescript starter template

### ISSUE THREAD

**Issue by guilherme-bragamonte** [commercetools/connect-application-kit#65]
### Issue summary
Error while running build command inside of typescript event starter template:
```shell
 *  Executing task: npm run build 


> event-typescript@1.0.0 build
> rimraf ./build && tsc

error TS5109: Option 'moduleResolution' must be set to 'Node16' (or left unspecified) when option 'module' is set to 'Node16'.


Found 1 error.
``` 

### Environment
Node: v16.20.2
Yarn: v1.22.19
NPM: 8.19.4
SO: Linux Ubuntu-based Elementary

**Comment by ruidias-commercetools** [comment]
@guilherme-bragamonte, a new version of the package was launched today. You are now able to run `npm run build` without any errors.

Thanks - Connect team
