### ISSUE TITLE
Typescript template for service does not call controller

### ISSUE THREAD

**Issue by phofmann** [commercetools/connect-application-kit#80]
The file https://github.com/commercetools/connect-application-kit/blob/main/application-templates/typescript/service/src/routes/service.route.ts currently does not do to much. I would expect it to call the post method of https://github.com/commercetools/connect-application-kit/blob/main/application-templates/typescript/service/src/controllers/service.controller.ts to actually do something.

**Comment by ruidias-commercetools** [comment]
This issue is being addressed in #83
